export const FETCH_BILL = 'FETCH_BILL';
export const FETCH_SINGLE_BILL = 'FETCH_SINGLE_BILL';
export const FETCH_SINGLE_BILL_BY_ROOMID = 'FETCH_SINGLE_BILL_BY_ROOMID';
export const CREATE_BILL = 'CREATE_BILL';