export const FETCH_POSTS_DATA = "FETCH_POSTS_DATA"
export const SUCCESS = "SUCCESS";
export const FAILD = "FAILD";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILD = "FETCH_USER_FAILD";

export const ADD_APARTMENT = "ADD_APARTMENT";